// <auto-generated />
using System;
using EasyPC.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyPC.Services.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260115120000_AddWishlist")]
    partial class AddWishlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a partial migration - only adding Wishlist table
        }
    }
}
