// <auto-generated />
using System;
using EasyPC.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyPC.Services.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260112120001_AddPaymentIds")]
    partial class AddPaymentIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // DbSet configurations would be here from DatabaseContext
#pragma warning restore 612, 618
        }
    }
}
